# .buildkite/pipeline.yml

env:
  IMAGE_REPO: "ghcr.io/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}"
  CONTAINER_NAME: "buildkite-hello-world-go-service"

steps:
  # This single step now handles the entire CI/CD process
  - label: "📦 Build and Deploy"
    if: build.pull_request.id == null
    command: |
      # Ensure script exits immediately if any command fails
      set -euo pipefail

      # --- 1. Login to GHCR ---
      echo "--- Logging in to GHCR ---"
      buildkite-agent secret get GHCR_TOKEN | docker login ghcr.io -u "${BUILDKITE_ORGANIZATION_SLUG}" --password-stdin

      # --- 2. Generate Image Tag ---
      echo "--- Generating Image Tag ---"
      COMMIT_SHORT_SHA=$(echo "${BUILDKITE_COMMIT}" | cut -c1-8)
      BUILD_DATE=$(date -u +%Y%m%d)
      IMAGE_TAG="${BUILD_DATE}.${BUILDKITE_BRANCH}.${COMMIT_SHORT_SHA}"
      FULL_IMAGE_NAME="${IMAGE_REPO}:${IMAGE_TAG}"
      echo "Full Image Name: ${FULL_IMAGE_NAME}"

      # --- 3. Build the Image ---
      echo "--- Building image: ${FULL_IMAGE_NAME} ---"
      docker build -t "${FULL_IMAGE_NAME}" .
      
      # --- 5. Deploy the Image ---
      echo "--- Deploying image ${FULL_IMAGE_NAME} ---"
      docker stop "${CONTAINER_NAME}" || true
      docker rm "${CONTAINER_NAME}" || true
      docker run -d -p 8080:8080 --name "${CONTAINER_NAME}" --restart always "${FULL_IMAGE_NAME}"
      
      echo "✅ Build and Deployment successful!"