# .buildkite/pipeline.yml

env:
  IMAGE_REPO: "ghcr.io/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}"
  CONTAINER_NAME: "buildkite-hello-world-go-service"

steps:
  # 步骤 1: 显式登录
  - label: "🔑 Login to GHCR"
    key: "login"
    if: build.pull_request.id == null
    command: |
      echo "--- Logging in to GHCR ---"
      buildkite-agent secret get GHCR_TOKEN | docker login ghcr.io -u "${BUILDKITE_ORGANIZATION_SLUG}" --password-stdin

  # 步骤 2: 使用原生 command 步骤进行构建和推送
  - label: "📦 Build and Push Image"
    key: "build-and-push"
    depends_on: "login"
    if: build.pull_request.id == null
    command: |
      set -euo pipefail
      
      echo "--- Generating Image Tag ---"

      # 步骤 2.1: 获取并验证短 Commit SHA
      COMMIT_SHORT_SHA=$(echo "${BUILDKITE_COMMIT}" | cut -c1-8)
      echo "1. Short Commit SHA: ${COMMIT_SHORT_SHA}"

      # 步骤 2.2: 获取并验证日期
      BUILD_DATE=$(date -u +%Y%m%d)
      echo "2. Build Date: ${BUILD_DATE}"

      # 步骤 2.3: 构造并验证最终的镜像标签
      IMAGE_TAG="${BUILD_DATE}.${BUILDKITE_BRANCH}.${COMMIT_SHORT_SHA}"
      echo "3. Final Image Tag: ${IMAGE_TAG}"

      FULL_IMAGE_NAME="${IMAGE_REPO}:${IMAGE_TAG}"
      echo "4. Full Image Name: ${FULL_IMAGE_NAME}"
      
      echo "--- Building image: ${FULL_IMAGE_NAME} ---"
      docker build -t "${FULL_IMAGE_NAME}" .

      echo "--- Pushing image: ${FULL_IMAGE_NAME} ---"
      docker push "${FULL_IMAGE_NAME}"
      
      buildkite-agent meta-data set "image-tag" "${IMAGE_TAG}"

  # 步骤 3: 手动批准
  - block: "🚀 Deploy to Production"
    fields:
      - text: "Image Tag"
        key: "image-tag-to-deploy"
        default: "$(buildkite-agent meta-data get 'image-tag')"

  # 步骤 4: 执行部署
  - label: "🚀 Executing Deployment"
    command: |
      set -euo pipefail
      IMAGE_TAG=$(buildkite-agent meta-data get "image-tag")
      
      echo "--- Deploying image ${IMAGE_TAG} ---"
      
      buildkite-agent secret get GHCR_TOKEN | docker login ghcr.io -u "${BUILDKITE_ORGANIZATION_SLUG}" --password-stdin

      docker pull "${IMAGE_REPO}:${IMAGE_TAG}"
      docker stop "${CONTAINER_NAME}" || true
      docker rm "${CONTAINER_NAME}" || true
      docker run -d -p 8080:8080 --name "${CONTAINER_NAME}" --restart always "${IMAGE_REPO}:${IMAGE_TAG}"
      
      echo "✅ Deployment successful!"