# .github/workflows/ci-build-and-dispatch.yml

name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-and-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 这一步依然是必要的，确保我们有完整的 Git 历史
          fetch-depth: 0

      # 2. 登录到 GitHub Container Registry (GHCR)
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. 【新增步骤】手动获取短 Commit ID
      - name: Get short commit SHA
        id: vars # 给这个步骤一个ID，方便后面引用
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # 4. 动态提取 Docker 镜像的元数据
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            # 【修改】不再使用 {{sha-short}}
            # 直接使用上一步 (id: vars) 的输出 (outputs.sha_short)
            type=raw,value={{date 'YYYYMMDD'}}.{{branch}}.${{ steps.vars.outputs.sha_short }},event=branch,priority=200

      # 5. 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # 6. 远程触发 Jenkins CD 作业
      - name: Trigger Jenkins CD Job
        run: |
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d ',' -f 1 | sed 's#ghcr.io/${{ env.IMAGE_NAME }}:##')
          echo "Generated Docker tag is: $IMAGE_TAG"
          
          curl -X POST "${{ secrets.JENKINS_URL }}/job/hello-world-cd/buildWithParameters" \
            --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
            --data token="${{ secrets.JENKINS_CD_JOB_TOKEN }}" \
            --data IMAGE_TAG="$IMAGE_TAG"