# .github/workflows/ci-build-and-dispatch.yml

name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-and-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 登录 GHCR
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. 手动获取短 Commit ID 和 Commit Message
      - name: Get Git metadata
        id: git_vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          # 将 commit message 中的换行符等特殊字符进行 URL 编码，以安全地传递
          echo "commit_message=$(git log -1 --pretty=%B | sed -z 's/\n/\\n/g' | jq -s -R -r @uri)" >> $GITHUB_OUTPUT

      # 4. 提取 Docker 元数据
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value={{date 'YYYYMMDD'}}.{{branch}}.${{ steps.git_vars.outputs.sha_short }},event=branch,priority=200

      # 5. 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # 6. 远程触发 Jenkins CD 作业
      #    --- 这是本次修改的核心部分 ---
      - name: Trigger Jenkins CD Job
        run: |
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | cut -d ',' -f 1 | sed 's#ghcr.io/${{ env.IMAGE_NAME }}:##')
          echo "Generated Docker tag is: $IMAGE_TAG"
          
          # 【修改】在 curl 命令中添加新的 --data 参数
          curl -X POST "${{ secrets.JENKINS_URL }}/job/hello-world-cd/buildWithParameters" \
            --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }} \
            --data token="${{ secrets.JENKINS_CD_JOB_TOKEN }}" \
            --data IMAGE_TAG="$IMAGE_TAG" \
            --data COMMIT_AUTHOR="${{ github.actor }}" \
            --data COMMIT_MESSAGE="${{ steps.git_vars.outputs.commit_message }}" \
            --data COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"