name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - classic

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure Git for private repos
      run: |
        git config --global url."https://${{ secrets.API_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Extract and Normalize Variables
      run: |
        echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_ENV

    - name: Generate timestamp for Beijing time
      run: |
        # 生成北京时间格式的时间戳 (UTC+8)
        YEAR_LAST_DIGIT=$(TZ='Asia/Shanghai' date '+%Y' | tail -c 2)
        TIMESTAMP=$(TZ='Asia/Shanghai' date "+${YEAR_LAST_DIGIT}%m%d%H%M")
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.API_TOKEN }}
        
    - name: Build Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build \
        --secret id=api_token,env=API_TOKEN \
        -t ghcr.io/${{ env.REPO_OWNER }}/jenkins-cicd-example:${{ env.TIMESTAMP }} .
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ env.REPO_OWNER }}/jenkins-cicd-example:${{ env.TIMESTAMP }}